/************************************************************************************************************************************/
/** @file		main.c
 * 	@brief		x
 * 	@details	x
 *
 * 	@author		Justin Reina, Firmware Engineer, Company Name
 * 	@orig		Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-10-23
 * 	@created	10/23/18
 * 	@last rev	x
 *
 *
 * 	@notes		x
 *
 * 	@section	Opens
 * 			none current
 *
 * 	@section	Legal Disclaimer
 * 			Copyright (c) 2018 STMicroelectronics
 */
/************************************************************************************************************************************/
#include "main.h"


/************************************************************************************************************************************/
/**	@fcn		int main(void)
 *  @brief		program main routine
 *  @details	x
 */
/************************************************************************************************************************************/
int main(void) {
  uint32_t ii = 0;

  /* @todo 	Add your application code here */
  for(;;) {
       ii++;
  }

  return EXIT_SUCCESS;
}

